remote_theme: just-the-docs/just-the-docs
title: Mi Create
description: Documentation for Mi Create
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://ooflet.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "https://ooflet.github.io/docs/Images/docs_icon.png"

color_scheme: BetterDarkTheme
search_enabled: true
# Aux links for the upper right navigation
aux_links:
  "Github":
    - "https://github.com/ooflet/mi-create"

callouts:
  info:
    title: Info
    color: white
    opacity: 0.3
  warning:
    title: Warning
    color: yellow
    opacity: 0.3
