site_name: Mi Create Documentation
repo_url: https://github.com/ooflet/Mi-Create
repo_name: ooflet/mi-create
theme:
  name: material
  custom_dir: overrides
  logo: Images/docs_icon.svg
  favicon: Images/favicon.png
  font: 
    text: Inter
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.tabs
    - navigation.top
    - navigation.instant.progress
    - navigation.footer

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# extra:
#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: Русский
#       link: /ru/
#       lang: ru

nav:
  - Home: index.md
  - Quickstart:
    - Introduction: quickstart/intro.md
    - Testing: quickstart/testing.md
    - Publishing: quickstart/publishing.md
  - Widgets:
    - Images: widgets/image.md
    - Digital Numbers: widgets/number.md
  - Customization: customization.md
  - Contributing: contributing.md