site_name: Mi Create Documentation
repo_url: https://github.com/ooflet/Mi-Create
repo_name: ooflet/mi-create
theme:
  name: material
  custom_dir: overrides
  logo: Images/docs_icon.png
  favicon: Images/favicon.png
  palette: 
  
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  features:
    - header.autohide
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# extra:
#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: Русский
#       link: /ru/
#       lang: ru

nav:
  - Home: index.md
  - Quickstart:
    - Introduction: quickstart/intro.md
    - Testing: quickstart/testing.md
    - Publishing: quickstart/publishing.md
  - Widgets:
    - Images: widgets/image.md
  - Customization: customization.md
  - Contributing: contributing.md